version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 10
  reviewers:
  - crackofdusk
  ignore:
  - dependency-name: socket.io
    versions:
    - 4.0.0
